frequency: 50
silent_tf_failure: false
sensor_timeout: 0.1
two_d_mode: false
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
debug: false
publish_tf: false
publish_acceleration: false
permit_corrected_publication: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom

# IPT
# Fuse x, y, z and euler angles
# Publish in frame "odom"
# Covariance undetermined
pose0: ipt/pose_cov
pose0_config: [true, true, true,
    true, true, true,
    false, false, false,
    false, false, false,
    false, false, false]
    
# UWB
# Fuse x, y, z
# Publish in frame "uwb"
# Covariance is specified in its datasheet
pose1: uwb/pose_cov
pose1_config: [true, true, true,
    false, false, false,
    false, false, false,
    false, false, false,
    false, false, false]


